_target_: pinnstorch.models.PINNModule
_partial_: true
loss_fn: mse
jit_compile: false
amp: false
lazy: false
cudagraph_compile: false
inline: false
optimizer:
  _target_: torch.optim.Adam
  _partial_: true
  # capturable: true
scaler:
  _target_: torch.cuda.amp.GradScaler